### ISSUE TITLE
Bug no Wiki

### ISSUE THREAD

**Issue by Leoo027** [LorittaBot/DreamLand#103]
**Qual é o problema?**

O problema éh q eu usei o +wiki Peculiar... Porém a descrição da wiki não foi...

Print: https://cdn.discordapp.com/attachments/734160231986102312/849422478312210432/unknown.png

**Como reproduzir o problema?**

Imagino que em algumas wikis estão assim, não sei mt bem se é um bug mais ok...

**Considerações Finais**

https://cdn.discordapp.com/attachments/840964885520449577/849422816701186058/809408543321096223.png

**Comment by joaoesteves10** [comment]
A descrição do artigo apareceu corretamente (`Peculiar pode referir-se a:`), o problema é que nesse tipo de páginas da Wikipédia (desambiguação), a informação relevante não está na descrição mas sim em listas abaixo dela, já que página é formada maioritariamente por links. 

A Loritta só mostra a descrição porque para a grande maioria dos artigos da Wikipédia não seguem este padrão, e a descrição é mais que suficiente para entender na generalidade o assunto pesquisado; assim sendo, não há muito o que fazer, já que mostrar o resto seria inviável porque resultaria em flood, mesmo que estivesse limitado a este tipo de páginas, pelo que fecharei a issue.

Nesse caso em particular, posso recomendar o uso do comando `+dicio`, que mostraria o que você provavelmente queria ver com o `+wiki`, o significado da palavra peculiar:

![Discord_7LpeJKBhn3](https://user-images.githubusercontent.com/25515504/127426626-797cd7d6-567b-483a-a7bf-346eef3f3d31.png)
