### ISSUE TITLE
+sonhos top

### ISSUE THREAD

**Issue by C0dezin** [LorittaBot/DreamLand#107]
**Qual é o problema?**
O +sonhos top retira imagem not be null

Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

1. Digitar +sonhos top
3. E vai acontecer
![Screenshot_20210606-122041_Discord-Beta](https://user-images.githubusercontent.com/73194980/120930038-f49f4b00-c6c1-11eb-93af-e66c2ad0a326.jpg)

4. Se quiser, pode colocar fotos!

**Considerações Finais**

**Comment by joaoesteves10** [comment]
O bug aparenta estar resolvido.
