### ISSUE TITLE
Insignias

### ISSUE THREAD

**Issue by mekbronk** [LorittaBot/DreamLand#112]
Desculpa por falar de novo isso mais é que queria comenta mais uma coisa, então, sabe as insígnias que aparecem no perfil quando coloca o comando +perfil? Então, acho que deveria ter um aba do site da lorita em que dê para vê da onde vem essa insígnia, pq tenho várias, mais tenho uma que NN quero, mais NN sei de que server veio, e seria legal ver os insignias dos servers para caso eu queira entrar eu acho, é só uma sugestão, por favor NN me bane lori, e se desse para configurar qual insígnia aparece no perfil seria bom

**Comment by MrPowerGamerBR** [comment]
Duplicado: https://github.com/LorittaBot/DreamLand/issues/111
