### ISSUE TITLE
Badge Faltando no FAQ

### ISSUE THREAD

**Issue by JapaSpirit** [LorittaBot/DreamLand#114]
**Qual é o problema?**

Está faltando informação no FAQ do site

**Como reproduzir o problema?**

1. Ao abrir o FAQ no site: https://loritta.website/br/extras/faq-loritta/profile-badges-meanings está faltando a badge do Gartic que tem no meu perfil e eu não faço a minima idéia do que significa.
![Screenshot_148](https://user-images.githubusercontent.com/82131268/121526515-d2624180-c9cf-11eb-820e-9609040e3eb2.png)

**Comment by MrPowerGamerBR** [comment]
> Badges que não estão aqui são de servidores parceiros meus ou de pessoas que doaram pra mim
