### ISSUE TITLE
Layout "Simplesmente Verde com Flores"

### ISSUE THREAD

**Issue by Feh2007** [LorittaBot/DreamLand#118]
**Qual é o problema?**

Eu já tive esse problema com o mesmo layout antes e havia sido resolvido, mas agora o problema voltou, o layout "Simplesmente verde com flores" fica com as informações no lugar incorreto.

**Como reproduzir o problema?**

1. Obtenha o layout "Simplesmente verde com flores"
2. Equipe-o
3. Observe o perfil
4. E então, você vai perceber que as informações estão em cima da linha.

**Considerações Finais**

(Aliás, não estou conseguindo anexar uma imagem pra mostrar o bug, mas tentem reproduzir ele por favor)

**Comment by MrPowerGamerBR** [comment]
Você já denunciou isso antes, a gente ainda nem arrumou isso https://github.com/LorittaBot/DreamLand/issues/118

E eu acho que o problema é devido ao tamanho do nome do servidor, por isso você "acha" que tinha sido corrigido mas na verdade era só porque você acabou usando o perfil em outro servidor.
