### ISSUE TITLE
Usuário banido consegue usar comandos slash

### ISSUE THREAD

**Issue by ThiagoMCastro** [LorittaBot/DreamLand#119]
**Qual é o problema?**

Fui banido de usar a Loritta em 2020, e abandonei a conta. E hoje fui entrar na mesma conta para ver como estavam as coisas, e fui executar um comando slash da loritta, e funcionou.
Ou seja, usuários banidos conseguem utilizar comandos slash da Loritta

**Como reproduzir o problema?**

1. Seja banido
2. Use um slash command

Print onde mostra que é possivel usar um slash command, junto com meu banimento
![image](https://user-images.githubusercontent.com/48470238/122144327-a3155f80-ce29-11eb-966a-374a25fe0186.png)

**Comment by MrPowerGamerBR** [comment]
Bug conhecido, eu não fiz sistema de ban em slash commands pois ainda nenhum dos comandos interagem com a economia

**Comment by MrPowerGamerBR** [comment]
Corrigido em https://github.com/LorittaBot/Loritta/pull/2468
