### ISSUE TITLE
Comandos funcionando blacklist

### ISSUE THREAD

**Issue by DarkCodeofc** [LorittaBot/DreamLand#121]
**Você pode usar comandos da loritta estando banido dela, por ex: +clear não vai funcionar mas se você usar /clear ele ja funciona**

Provavelmente vocês esqueceram de botar um "if" nos comandos de /

**usando qualquer comando com / o que veio nessa atualização do discord.**

1. Bug achado recentemente.
2. Colocar um "if"
3. teste com alguem banido, use /ban ou /clear
4. Se quiser, pode colocar fotos!

**Comment by joaoesteves10** [comment]
Repetido de #119
