### ISSUE TITLE
Sugestão para o comando +userinfo.

### ISSUE THREAD

**Issue by IKaoruChanI** [LorittaBot/DreamLand#122]
**Qual é a sua sugestão?**

Adição da mensagem do novo sobre mim do Discord nas informações do comando userinfo.
[Aqui um exemplo de como poderia ser.](https://cdn.discordapp.com/attachments/573641214356619274/855215835755839488/unknown.png)

**Porque a sua sugestão deve ser adicionada na Loritta?**

Seria útil para o comandos após a atualização de perfil do Discord for lançada, estar completo e de uma forma ainda organizada como já é.

**Comment by PeterStark000** [comment]
Temos sim a ideia de adicionar esta informação no userinfo (ou em um comando específico para isso), porém atualmente esta informação não está visível para bots como a Loritta e nem sabemos se será (como diz [aqui nesta issue](https://github.com/LorittaBot/DreamLand/issues/17#issuecomment-864585305) fixada), pois isso implica um pouco na questão de privacidade de usuário, mas se por acaso essa informação vir a se tornar pública para bots, aí sim poderemos fazer o comando.
