### ISSUE TITLE
Criação do comando +userbanner.

### ISSUE THREAD

**Issue by IKaoruChanI** [LorittaBot/DreamLand#123]
**Qual é a sua sugestão?**
Um novo comando que mostrasse os novos banners do seu perfil ou dos usuários, assim como mostra avatares utilizando +userbanner ou +profilebanner, a pessoa poderia escolher no painel dashboard para que a visibilidade do seu banner pelo comando fosse desativada ou ativada e quem tentasse receberia uma mensagem avisando.

**Porque a sua sugestão deve ser adicionada na Loritta?**
Seria interessante já que possuem outros comandos e/ou formas de ver banners de servidores e de backgrounds de convites dos servidores.

**Comment by MatadorProBr** [comment]
https://github.com/LorittaBot/DreamLand/issues/17#issuecomment-864585305
