### ISSUE TITLE
Erro ao tentar pegar o daily

### ISSUE THREAD

**Issue by George1655** [LorittaBot/DreamLand#124]
**Qual é o problema?**
Erro de java ao tentar pegar o daily.

Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

O bug apareceu, quando eu tentei pegar o daily, autorizei a conta, ai fui direcionado para a dashboard e deu um erro.
![erro](https://user-images.githubusercontent.com/56810520/122605264-95d8ba80-d04d-11eb-8039-86e3970e31d9.png)

**Comment by MrPowerGamerBR** [comment]
Já foi arrumado, eu não sei o que aconteceu mas parece que foi que o container ficou sem internet e não estava conseguindo descobrir o domínio do Discord (DNS).
