### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by Zolinhoozinho** [LorittaBot/DreamLand#125]
**Qual é a sua sugestão?**

Quando usar o “+say” ao invés de usa a lori usa uma webhook

**Porque a sua sugestão deve ser adicionada na Loritta?**

Pois é chato fica com “mensagem enviada por (blablabla) ai se usa uma webhook n teria q usar isso

**Comment by joaoesteves10** [comment]
A única maneira de evitar o "mensagem enviada por" seria enviar a mensagem pela webhook usando o nome e avatar da pessoa que pediu o comando, o que vai contra o propósito do comando `+say`, que é enviar uma mensagem pela Loritta. 

Assim, o `+say` que propõe serviria apenas para enviar mensagens com a tag de BOT na mesma identidade que já usa, pelo que a sugestão, na sua forma atual, não me parece ser viável. Assim sendo, fecharei a issue.
