### ISSUE TITLE
Aparentemente a Loritta não tem mais espaço disponível 💀

### ISSUE THREAD

**Issue by nikkothemaster** [LorittaBot/DreamLand#127]
**Qual é o problema?**

Ao dar o comando `+inviteinfo`, por exemplo, a Loritta envia um erro:
`org.postgresql.util.PSQLException: ERROR: could not access status of transaction 0
  Detail: Could not write to file "pg_subtrans/3D4F" at offset 57344: No space left on device.`

**Como reproduzir o problema?**

1. Dar alguns comandos específicos, como `+inviteinfo` (Eu não sei se o problema é com mais de um comando)

**Comment by MrPowerGamerBR** [comment]
Já foi arrumado!
