### ISSUE TITLE
Personalização de Perfil

### ISSUE THREAD

**Issue by Maykoo** [LorittaBot/DreamLand#128]
**Qual é a sua sugestão?**

Como nós sabemos, O Discord melhorou a personalização de perfil com Sobre Mim e Banner. Eu gostaria de um comando que disponibiliza pegar ou ver o banner de um usuário.

**Porque a sua sugestão deve ser adicionada na Loritta?**

Ai me fode po

**Considerações Finais**

Beba água!

**Comment by DarkAngel5965** [comment]
Mas nem lançou ainda.

**Comment by PeterStark000** [comment]
Foi explicado aqui [nesta issue](https://github.com/LorittaBot/DreamLand/issues/17#issuecomment-864585305) que não estamos aprovando sugestões desde tipo, pois é algo que não está sobre nosso alcance.
