### ISSUE TITLE
@everyone

### ISSUE THREAD

**Issue by Maykoo** [LorittaBot/DreamLand#129]
https://img.ifunny.co/images/b974f672c5f51d267378445ac291b22b3e78ecdab7d4c61795fa687020a4564b_1.webm.gif
https://img.ifunny.co/images/b974f672c5f51d267378445ac291b22b3e78ecdab7d4c61795fa687020a4564b_1.webm.gif
https://img.ifunny.co/images/b974f672c5f51d267378445ac291b22b3e78ecdab7d4c61795fa687020a4564b_1.webm.gif
♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CA♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★�CAVALO★§�DE★§�§TROIA♘ ♞HERON★ @everyone @everyone

**Comment by AzureSky21** [comment]
Trava GitHub, emocionante

**Comment by DarkAngel5965** [comment]
pior que ele marcou uma organização kkkkkkkk

**Comment by RodasOwO** [comment]
Trava Webhookkkkkkkkkkk
