### ISSUE TITLE
Automod

### ISSUE THREAD

**Issue by fbrrafa** [LorittaBot/DreamLand#130]
**Qual é a sua sugestão?**

Já passaram vários anos falando "em breve terá" e nunca mais é adicionado função automoderacao estilo a do mee6

**Porque a sua sugestão deve ser adicionada na Loritta?**

Para todos pararem de utilizar o mee6/dyno pra essa função e poder fazer tudo na lori

**Considerações Finais**

Apoio o tráfico de anões bolivianos

**Comment by PeterStark000** [comment]
Ainda temos interesse em adicionar um módulo sobre porém.. Sobre o motivo de não estarmos adicionando nenhuma dessas sugestões no momento:
- Atualmente o website da Loritta está com o código um pouco antigo e que precisa passar por mudanças, principalmente tudo que envolve o dashboard;
- Sendo assim, é cada vez mais complicado ficar adicionando novas features e módulos no dashboard da Loritta, estamos evitando adicionar agora, para evitar futuros problemas e mais bagunças nos código.

Mas assim que terminamos tudo, adicionaremos todas as sugestões que estão no estado de **"em breve adicionaremos"**.
