### ISSUE TITLE
Loritta considera uma String como um long

### ISSUE THREAD

**Issue by rodovia** [LorittaBot/DreamLand#131]
**Qual é o problema?**

A Loritta considera uma String (nesse contexto, parte do nome de um canal) como um ID longo.

**Como reproduzir o problema?**

1. Use o comando `channelinfo` com qualquer nome como argumento

**Resultado esperado**: Ela enviar o embed com as informações sobre o chat
**Resultado recebido**: 

![Resultado do bug](https://user-images.githubusercontent.com/64744799/122683371-078f4080-d1d5-11eb-919b-746d9f0b9236.png)

**Comment by DarkAngel5965** [comment]
Você tem que mencionar o canal que você quer ver as informações ou botar o ID.

**Comment by rodovia** [comment]
Eu não consigo ver o canal

Em seg, 21 de jun de 2021 10:22, DarkAngel5965 ***@***.***>
escreveu:

**Comment by DarkAngel5965** [comment]
Então por isso não funciona, você não tem permissão.

**Comment by joaoesteves10** [comment]
Embora a mensagem de erro possa ser melhorada, este é o comportamento esperado, uma vez que um comando deste tipo só deveria funcionar com a marcação ou ID do canal, por motivos óbvios de segurança. Assim sendo, fecharei a issue.
