### ISSUE TITLE
Aniversario

### ISSUE THREAD

**Issue by Zumoka** [LorittaBot/DreamLand#132]
**Qual é a sua sugestão?**

Adicionar um comando de aniversario na Loritta (Tipo o MEE6) para poder lembrar um usuario de seu aniversario.
Sei que pode parecer generico, pois ja tem o comando de lembetes, mas seria realmente muito legal um comando na Loritta que lembrasse o aniversario de alguem ("Parabéns (user-legal), hoje é seu aniversario!)

**Porque a sua sugestão deve ser adicionada na Loritta?**

Por que ela é uma sugestão boa kk

**Considerações Finais**

Trafiquem nesquik

**Comment by DarkAngel5965** [comment]
O power disse que já vai adicionar isso:
https://github.com/LorittaBot/DreamLand/issues/17#issuecomment-821993114
