### ISSUE TITLE
Votei 61 vezes no top.gg e não ganhei a recompensa

### ISSUE THREAD

**Issue by andreasgrum00** [LorittaBot/DreamLand#133]
**Qual é o problema?**

Alguns dias atrás deu um bug na Loritta que ela não avisava quando tu votou nela no top.gg. Eu consegui 60 votos e a Lori nn me mandou a mensagem. 

![image](https://user-images.githubusercontent.com/55033182/122831791-c96f4b00-d2c0-11eb-818a-becba8b57856.png)

Tá aí uma foto de gatinho pra ti :)
![image](https://user-images.githubusercontent.com/55033182/122831967-0b988c80-d2c1-11eb-9c73-b6b85d721c59.png)

**Comment by joaoesteves10** [comment]
Mesmo que você não tenha recebido a mensagem, você ainda recebeu a sua key dos 60 votos, ela deve estar disponível no seu [dashboard](https://loritta.website/dashboard).

Como não é uma sugestão vou fechar a issue, caso precise de ajuda com a Lori no futuro, use o nosso [servidor de suporte](https://discord.gg/loritta).
