### ISSUE TITLE
Comando +banner

### ISSUE THREAD

**Issue by MINATO0912** [LorittaBot/DreamLand#135]
**Qual é a sua sugestão?**

Ter o comando de +banner na loritta

**Porque a sua sugestão deve ser adicionada na Loritta?**

Para as pessoas verem os banners das outras pessoas assim como o +avatar

**Comment by MatadorProBr** [comment]
Por favor antes de fazer uma sugestão leia o que você não deve sugerir
https://github.com/LorittaBot/DreamLand/issues/17#issuecomment-864585305
