### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by baiconhair** [LorittaBot/DreamLand#137]
**Qual é a sua sugestão?**
ter um comando chamado +addsticker, por causa da nova função de adicionar stickers personalizados.

**Porque a sua sugestão deve ser adicionada na Loritta?**
Facilitar a criar stickers para o seu servidor

**Considerações Finais**
:)

**Comment by baiconhair** [comment]
**Qual é a sua sugestão?**
ter um comando chamado +addsticker, por causa da nova função de adicionar stickers personalizados.

**Porque a sua sugestão deve ser adicionada na Loritta?**
Facilitar a criar stickers para o seu servidor

**Considerações Finais**
:)

**Comment by MatadorProBr** [comment]
Acho que séria melhor mudar o nome da sugestão para "Adicionar o comando +addsticker"
