### ISSUE TITLE
stickers

### ISSUE THREAD

**Issue by PFGamerFP** [LorittaBot/DreamLand#139]
**Qual é a sua sugestão?**
 Acho que já deve ter recebido esta sugestão, +addsticker

Sugestão incrível maravilhosa chocante que vai arrebentar o mundo...

**Porque a sua sugestão deve ser adicionada na Loritta?**
Para combinar com o +addemoji

Texto texto texto texto texto...

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

**Comment by baiconhair** [comment]
é né que copiou a minha ,-,
