### ISSUE TITLE
Usar comandos mesmo banido 

### ISSUE THREAD

**Issue by LMS5413** [LorittaBot/DreamLand#140]
**Qual é o problema?**

O meu amigo foi banido da loritta e pela surpresa dele tinha uma falha que poderia usar comandos da loritta mesmo banido, era só executar comandos via slash commands que executaria normalmente

**Como reproduzir o problema?**

Bane uma pessoa
E use o slash commands com a pessoa banida

**Comment by MrPowerGamerBR** [comment]
Duplicata https://github.com/LorittaBot/DreamLand/issues/119
