### ISSUE TITLE
Bug no +clean

### ISSUE THREAD

**Issue by rafaelbastoss** [LorittaBot/DreamLand#143]
O +clean está bugado, mesmo com a permissão e tudo, ela manda que as mensagens foram apagadas, mas não são.

**Comment by joaoesteves10** [comment]
Uma vez que a Lori disse que apagou as mensagens, o que aconteceu é provavelmente um bug visual do Discord ou o resultado de alguma instabilidade temporária que a Lori possa ter sofrido nesse período, e visto que não temos instruções de como reproduzir fecharei a issue. 

Caso o problema se repita ou tenha mais dificuldades no futuro, não hesite em contactar-nos através do nosso [servidor de suporte](https://discord.gg/loritta), onde poderemos ajudar de uma forma mais imediata.
