### ISSUE TITLE
Sugestão que vai ajudar muito o bot

### ISSUE THREAD

**Issue by jonarasgames** [LorittaBot/DreamLand#148]
**Qual é a sua sugestão?**

É uma sugestão que tem no meu bot e que vai deixar bunitin, $nomention, Tipo, sei que não tem no .js mas que só tem no Dbd mas tem um jeitin de fazer isso, mas antes deixe explicar:
$nomention é um código que faz o bot responder um Comando sem marcar o usuário que botou o comando, assim deixando mais bunitu e sem deixar os caras com raiva de marcação, e sei que existe 1 deles no mundo, e eu sou 1 deles

**Porque a sua sugestão deve ser adicionada na Loritta?**

Como eu disse ai em cima, pra ficar bunitin e pá não deixar os caras com raiva de marcação toda hora, só deixa em comandos importantes tipo o de lembrete que precisa marcar aí não precisa botar nomention, mas nos restos sim

**Considerações Finais**

Meu bot não é melhor do que a loritta, mas ele é nice, Jonaras Bot, tú precisa conhecer, pesquisa no Google e procure oxx k
https://media.discordapp.net/attachments/844655653779669002/863025517518127104/IMG_20210709_085512.png

**Comment by AzureSky21** [comment]
1. DBD é uma merda que nem deveria ser considerado como uma lang.
2. Loritta é em Kotlin, não JS.
3. É uma menção. **SÓ UMA MENÇÃO, SÓ VOCÊ ACHA IRRITANTE UMA MARCAÇÃO DE UMA MENSAGEM QUASE INSTANTÂNEA.** 
4. Ah, como uma coisa dessas vai "ajudar muito bot"?

**Comment by Luis3736** [comment]
Na verdade, a Lori já faz o "responder" do Discord... Apenas acredito que é desnecessário continuar com a marcação, uma vez que já fica marcado apenas no responder...

**Comment by Pauloo27** [comment]
> 1. DBD é uma merda que nem deveria ser considerado como uma lang.
> 2. Loritta é em Kotlin, não JS.
> 3. É uma menção. **SÓ UMA MENÇÃO, SÓ VOCÊ ACHA IRRITANTE UMA MARCAÇÃO DE UMA MENSAGEM QUASE INSTANTÂNEA.**
> 4. Ah, como uma coisa dessas vai "ajudar muito bot"?

Calma lá campeão, a sugestão realmente é estranha e pareceu mais um ad do bot dele, mas não precisa começar a atacar até a "lang" (ou como quiser chamar) que ele usa.

**Comment by joaoesteves10** [comment]
Do meu ponto de vista, implementar esta sugestão não faria nada para "ajudar muito o bot", pelo contrário, resultaria num completo caos em canais de comandos públicos, uma vez que, ignorando a função de reply, os comandos não estariam marcados e seria impossível saber qual resposta é para quem.

Quanto à função de reply, e em resposta ao @Luis3736, embora inicialmente pareça que a marcação é redundante, ela serve o propósito de facilitar a identificação de quem executou o comando caso a pessoa delete a mensagem original, sendo assim extremamente importante em casos de quebra de regras com os comandos da Loritta. 
Para exemplificar, caso alguém usasse o comando `+avatar` para mostrar uma imagem NSFW e apagasse a mensagem original, não seria possível determinar quem pediu o comando caso o servidor não tivesse um canal de logs, uma vez que a marcação do autor não estaria na mensagem e a reply só diria que a mensagem original foi deletada.

Assim sendo, esta sugestão é inviável, pelo que fecharei a issue.
