### ISSUE TITLE
Sugestão mt top

### ISSUE THREAD

**Issue by SuperEric1** [LorittaBot/DreamLand#149]
**Qual é a sua sugestão?**

Anti link

**Porque a sua sugestão deve ser adicionada na Loritta?**

A loritta só tem anti discord invites,acho que um anti link deixaria ela mais útil do que já é!

**Comment by dittom20** [comment]
Pretendemos sim adicionar a função de bloquear outros links (não apenas invites) na Loritta, algum dia.
