### ISSUE TITLE
"Canais que serão proibido usar comandos"

### ISSUE THREAD

**Issue by 4nonima** [LorittaBot/DreamLand#150]
Eu configuro a Loritta para os usuários não executarem comandos no canal de texto, salvo a configuração, e ela simplesmente responde os comandos normalmente invés de dizer a mensagem que eu havia escrito.

Testei em outros servidores em que eu sou dona, e a configuração funcionou normalmente. Eu gostaria que ela funcionasse neste servidor também, obrigada por ler.

![help_me_please](https://user-images.githubusercontent.com/87210278/125139765-20598a80-e0df-11eb-9d1c-66cce5d5abbe.png)

(Obs: Isso foi a muito tempo, e eu já removi essa configuração já que ela não funcionava. Eu só lembrei disto e quis postar aqui.)

**Comment by DarkAngel5965** [comment]
Como você é dona/staff do servidor acredito que seu cargo tenha um bypass nisso.

**Comment by joaoesteves10** [comment]
Como dito acima, esse comportamento provavelmente deve-se às suas permissões. Se ainda for do seu interesse, tente configurar novamente a Loritta para ignorar os comandos como fez anteriormente e teste os comandos numa conta que não tenha owner nem cargos; o resultado deve ser o esperado, tal como verifica em outros servidores.

Como este problema não aparenta ser o resultado de um bug com a Loritta, fecharei a issue. Caso não consiga resolver o problema que descreveu ou tenha mais dificuldades no futuro, não hesite em contactar-nos através do nosso [servidor de suporte](https://discord.gg/loritta), onde poderemos ajudar de uma forma mais imediata.
