### ISSUE TITLE
Erro ao apagar 100 mensagens!

### ISSUE THREAD

**Issue by nathan-lucca** [LorittaBot/DreamLand#152]
**Qual é o problema?**

Quando eu tento executar o comando +clear 100 ou qualquer outra quantia, aparece um erro muito estranho.

**Como reproduzir o problema?**

1. Digite o comando +clear <quantia>

![image](https://user-images.githubusercontent.com/42450935/125172146-59046d00-e18e-11eb-97bc-2524d7eb8b14.png)

**Comment by DarkAngel5965** [comment]
A Loritta havia caído nessa hora.
