### ISSUE TITLE
Comando +banner

### ISSUE THREAD

**Issue by CakeUn** [LorittaBot/DreamLand#153]
**Qual é a sua sugestão?**
Adicionar um comando de +banner

**Porque a sua sugestão deve ser adicionada na Loritta?**
Nesses dias ocorreu uma atualização de banner animado, e sobre mim ..., se existe o comando +perfil ou +avatar poderia existir um +banner

**Comment by DarkAngel5965** [comment]
Já foi dito que ainda não foi documentado  como fazer um comando que mostre o banner!

**Comment by dittom20** [comment]
Leia https://github.com/LorittaBot/DreamLand/issues/17
