### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by VikunGS** [LorittaBot/DreamLand#158]
**Qual é a sua sugestão?**

+banner/+banner @usuario e mostrar o banner que você ou a pessoa marcada usa

**Porque a sua sugestão deve ser adicionada na Loritta?**

já que agora tem banner, acho que seria interessante adicionar um "+banner", visto que tem um "+avatar"

**Comment by dittom20** [comment]
Leia https://github.com/LorittaBot/DreamLand/issues/17
