### ISSUE TITLE
Comandos para adicionar, remover e ver stickers

### ISSUE THREAD

**Issue by Bl4ckberry** [LorittaBot/DreamLand#159]
**Qual é a sua sugestão?**

Adicionar comandos para adicionar, remover e ver os stickers dos servidores (semelhante aos comandos de emojis que a Lori já possuí)

**Porque a sua sugestão deve ser adicionada na Loritta?**

Considerando que a Loritta possuí diversas utilidades, poderia ser interessante ter esse acréscimo de comando. Querendo ou não os stickers estão ficando bem presentes nos servidores, então considero isso deverás útil e divertido, imagina só ser o primeiro bot com opção de acessar os stickers dos servidores, incrível não é? (Desculpa se foi inconveniente, eu entendo como deve dar trabalho pra vocês, mas ficaria muito feliz)

**Considerações Finais**

https://pin.it/6TROgPG muito fofinho 🥺

**Comment by kituroi** [comment]
acho que se já tivesse disponível na api eles já tinham adicionado

**Comment by joaoesteves10** [comment]
Duplicados: #137, #139 e #142. Uma vez que esta é a issue mais completa sobre o tópico, as restantes serão fechadas.
