### ISSUE TITLE
Banner do usuário 

### ISSUE THREAD

**Issue by sandaro77** [LorittaBot/DreamLand#161]
Agora com a nova função de banner do discord para os usuários de nitro acho que seria muito interessante já como existe o comando +avatar no bot da loritta acho que seria válido que fosse criado o comando +banner para poder ver os banners dos amiguinhos também.

meu usuário do discord: Sandaro#7777

**Comment by dittom20** [comment]
Leia https://github.com/LorittaBot/DreamLand/issues/17
