### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by Stelckis** [LorittaBot/DreamLand#163]
Então, eu usei um comando da loritta, e veio um possivel emoji que ela usa, mas não veio certo, apenas com o :emoji_nome:
não sei se é um bug, mas quis reportar mesmo assim

comando : /anagrama

![image](https://user-images.githubusercontent.com/85700525/127053653-b8123392-f2e3-46d7-9687-1138a5777fd8.png)

**Comment by DarkAngel5965** [comment]
A loritta possui permissão para utilizar emojis externos?

**Comment by joaoesteves10** [comment]
Para slash commands, o [minor] bug reportado verifica-se se a Loritta não tiver **expressamente** a permissão de usar emojis externos, ou seja, mesmo que ela tenha a permissão de Administrador, o problema ainda se verifica. 

Já para comandos diretos com o prefixo ou menção, caso ela não tenha a permissão ela avisa no chat, como mostrado abaixo; este é o intended behavior nesta situação.

![Discord_bxZp0lvIwi](https://user-images.githubusercontent.com/25515504/127423816-4f0de795-c443-461c-b584-f73c5899748e.png)

Assim, o problema pode ser resolvido do seu lado ativando a permissão de usar emojis externos para ela, tal como indicado na print.
