### ISSUE TITLE
Bug no comando +ship

### ISSUE THREAD

**Issue by PikachuVrasa** [LorittaBot/DreamLand#164]
**Qual é o problema?**

Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...
![image](https://user-images.githubusercontent.com/88043033/127169363-5da8f193-c5c5-4aa6-929c-97235785fccd.png)
Olá!! tem um bug no +ship que realmente não funciona, eu tentei inúmeras vezes, mas o +ship não funciona, espero que consigam arrumar!

**Comment by joaoesteves10** [comment]
O comando aparenta estar a funcionar corretamente, tente novamente e informe-nos se o erro se manter, caso contrário, feche a issue.

![image](https://user-images.githubusercontent.com/25515504/127411939-0f40b447-4130-4357-9a68-e292c9fda5b0.png)

**Comment by PikachuVrasa** [comment]
Sim!! o comando voltou ao normal, muito obrigado!
