### ISSUE TITLE
Bug no "retribuir" do Kiss

### ISSUE THREAD

**Issue by SonBane** [LorittaBot/DreamLand#167]
**Bug quando clica no emoji do "retribuir" no Kiss**

Basicamente quando você dá o comando +kiss aparece o botão de retribuir para a pessoa mencionada, mas se quem clica não for uma pessoa mencionada a loritta edita a mensagem e reseta o gif

**Como reproduzir o problema?**

1. De o comando +kiss mencionando alguem
2. Clique no emoji do retribuir

**Considerações Finais**

Gatinho fofo ayaya

**Comment by joaoesteves10** [comment]
Não consegui reproduzir o bug, embora ao reagir o gif pisque, a mensagem não fica com um indicador de que foi editada, e esse comportamento acontece com outros emojis, indicando que se trata de um bug visual do cliente do discord.
