### ISSUE TITLE
Nova funcionalidade de sonhos!!

### ISSUE THREAD

**Issue by Salluan** [LorittaBot/DreamLand#168]
Bom, ultimamente tem ficado uma idéia na minha mente que não queria sair, então irei apresenta-la,

Comando: +emprestar ou +colaborar 

Oque ele fazeria?

Bom, ele enviará o valor pra uma pessoa como 10k, e se a pessoa aceitar, ela ganhará 10k.

Oque isso mudaria do comando pay?

Bom se a pessoa não devolver os sonhos ate o fim do dia, o nome dela ficará como devendo, e ela receberá uma penalidade, como receber menos sonhos no daily, enfim voceis escolhem a penalidade.

E porque isso seria bom?

Bom vai que uma pessoa ta querendo apostar e ela ta sem dinheiro, ai você vai la e empresta 50k pra ela, e ela consegue ganhar varias apostas e fica com 200k, aii ela resolve não te devolver os 50k do início, ja com esse comando isso não existiria ja que a pessoa seria obrigada a devolver.

Bom isso só foi minha idéia, eu estou no teu server apartamento da loritta

Nome no discord: salluan

Id: 828067406948859956

**Comment by typpe** [comment]
Já fizeram essa sugestão e ela foi recusada.

**Comment by PeterStark000** [comment]
Olá tudo bem? Seguinte, esta sugestão já está listada na nossa issue fixada ("Lista de funcionalidades que você não deve sugerir") se caso você não tenha visto, lá nos colocamos os motivos do por que essas sugestão é complicada de se realizar, se você por acaso tem interesse em ver, [clique aqui](https://github.com/LorittaBot/DreamLand/issues/17#issuecomment-821993492)
