### ISSUE TITLE
Problema eu executar o comando "+clear"

### ISSUE THREAD

**Issue by ggomesGabriel** [LorittaBot/DreamLand#169]
**Qual é o problema?**
Estou tentando executar o comando '+clear' e o bot esta dando um problema.

Descrição maravilhosa sobre qual é o problema
ao executar o comando '+clear' a loritta da esse erro ('Alguma coisa deu extremamente errada ao executar este comando... Desculpe pela inconveniência. :lori_sob: org.postgresql.util.PSQLException: ERROR: could not access status of transaction 0
  Detail: Could not write to file "pg_subtrans/F80B" at offset 163840: No space left on device.').

print: https://i.imgur.com/QZMSIPE.png

**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...
![ab21d5b71ba7b3b74947c3e5656c6aee](https://user-images.githubusercontent.com/88249751/127749123-327280c9-3d2d-4482-ac2c-528f01ce7270.jpg)

**Comment by joaoesteves10** [comment]
O problema deve-se à instabilidade que a Loritta está a sofrer no momento, e deve resolver-se assim que ela voltar ao normal.
