### ISSUE TITLE
Bug comando "+remindme"

### ISSUE THREAD

**Issue by Meiotinhakkk** [LorittaBot/DreamLand#170]
**Qual é o problema?**

O problema encontrado foi no comando "+remindme", após o tempo inserido acabar, começa a falar que o tempo acabou diversas vezes sem parar

**Como reproduzir o problema?**

1. Escreva +remindme .
2. Coloque em seguida 5m
3. Caso aconteça o bug, vai aparecer a mesma mensagem várias vezes
4. 
![Screenshot_20210731-151039](https://user-images.githubusercontent.com/88249942/127749299-852508c1-cbc3-438f-8c08-c6a246d37ff6.png)
![Screenshot_20210731-151039](https://user-images.githubusercontent.com/88249942/127749307-13e9a2fe-188f-4db5-8ee5-960e597f1d95.png)

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção... 
![images - 2021-07-31T152336 183](https://user-images.githubusercontent.com/88249942/127749315-714ad6af-8aac-4b32-ac48-d258b3da3be1.jpeg)

**Comment by joaoesteves10** [comment]
O problema deve-se à instabilidade que a Loritta está a sofrer no momento, e deve resolver-se assim que ela voltar ao normal. No meio tempo, tirar a permissão dela de falar nesse chat pode ser uma boa opção para evitar spam.
