### ISSUE TITLE
Mudança sobre Sexualidade

### ISSUE THREAD

**Issue by CristalMoon3456** [LorittaBot/DreamLand#176]
**A minha sugestão é para trocar a sexualidade,para trans,gay,lésbica,etc.**

Sugestão incrível maravilhosa chocante que vai arrebentar o mundo...

**Porque a sua sugestão deve ser adicionada na Loritta?**
Pois isso vai ajudar MUITAS pessoas,e mostra respeito por todos que são LGBTQIA+.

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

**Comment by MrPowerGamerBR** [comment]
Não tem nenhum comando de "sexualidade" na Loritta exceto o `+gender`, que é usado para:
* Definir se vai aparecer um homem, mulher, ou aleatório, no comando de ações dela.
* Altera o pronome da pessoa ao usar `+rep`

Como também a sugestão falta explicações sobre o que você está falando para que seja aceita.
