### ISSUE TITLE
Falha na lorrita

### ISSUE THREAD

**Issue by LordDuckjs** [LorittaBot/DreamLand#179]
**Qual é o problema?**
Simples, qualquer pessoa pode criar um bot com bdfd, com o mesmo prefixo da lorrita e usar o comando kiss, ou ate marry, e outros, invés da lorrita recusar, ela apenas aceita
**O que voces podiam fazer para arrumar** --Essa seção foi feito por Lord Duck.
Fazer que o prefixo seje detectado com o argumento "Kiss" e então, deletar as 2 msg que for mandado pela pessoa e do bot com kiss, e recusar o comando kiss.

**Como reproduzir o problema?**

1. Usar um bot custom ou fazer um bot com o mesmo prefixo ou nao
2. Criar o comando kiss
3. Execute o kiss em lorrita
**EXTRA**
Isso conta com outros varios comandos que a lorrita recusa, etc..
Na verdade todos comandos que a lorrita recusa, pode ser totalmente duplicado em out--ro bot.

-Lord Duck.#0 0 0 1

**Comment by MrPowerGamerBR** [comment]
Acho que é meio óbvio que criar um comando igual ao da Loritta em outro bot e usar esse comando mencionando a Loritta, vai funcionar sem nenhum problema.

Como também é inviável a Loritta ficar filtrando comandos de kiss (e similares) de outros bots só por causa de um easter egg que existe nela.
