### ISSUE TITLE
Anti-NSFW

### ISSUE THREAD

**Issue by Azure142** [LorittaBot/DreamLand#18]
Colocar uma forma da Loritta detectar imagem NSFW, pessoalzin sem nada pra fazer usa +avatar em usuário com foto nsfw. Já vi gente dizendo com uma API que detecta NSFW, como existe pessoal que usa avatar e outros comandos de imagem pra ver imagens nsfw, pensei nessa sugestão.

**Comment by MrPowerGamerBR** [comment]
Na minha opinião quem deveria filtrar essas imagens é o próprio Discord, e não a Loritta.

Colocar um filtro antes de mostrar o avatar de uma pessoa, ou antes de fazer uma manipulação de imagem, iria fazer que demore mais tempo só para processar algo.

E é claro, filtros NSFW tem falsos positivos e falsos negativos, tanto que foi por isso que eu decidi não implementar um filtro NSFW em todos os comandos que usam imagens na Loritta.
