### ISSUE TITLE
Falha numero 2

### ISSUE THREAD

**Issue by LordDuckjs** [LorittaBot/DreamLand#180]
**Qual é o problema?**

Qualquer bot com comando de eval ou duplicar um comando e vars da lorrita(ou nao)
Praticamente todos os comandos que a lorrita recusa pode ser burlados

**Como reproduzir o problema?**

Crie um comando com o mesmo prefixo ou nao, Pode criar o marry,ship, kiss, etc..
Com o ship, e so fazer um comando com var ou nao, e setar com eval ou nao,
Então deixar a % do ship, setada fixo.
e sim pode burlar quase todos os comandos.

**Considerações Finais**
**e provas e tal pra vcs sabe**

https://media.discordapp.net/attachments/873612623097257994/873612856489308230/unknown.png?width=683&height=427

https://media.discordapp.net/attachments/873612623097257994/873612827728953344/unknown.png?width=683&height=427

https://media.discordapp.net/attachments/873612623097257994/873612635168440320/unknown.png?width=683&height=427

https://media.discordapp.net/attachments/873612623097257994/873612791985090590/unknown.png?width=683&height=427

**Como podem arrumar**:

Fazer que o bot consiga verificar qualquer tipo de prefixo usado e kiss, porem deve verificar tbm se esta mencionando lol, as vezes nao da pra arrumar

-Lord Duck.#0 0  0 1

**Comment by MrPowerGamerBR** [comment]
Duplicata e com a mesma justificativa de https://github.com/LorittaBot/DreamLand/issues/179
