### ISSUE TITLE
Respostas efêmeras para os slashs

### ISSUE THREAD

**Issue by JPBM135** [LorittaBot/DreamLand#191]
**Qual é a sua sugestão?**

Os erros e mensagens de aviso sobre alguma má funcionalidade em slashs ou qualquer interação poderiam ser "secretas" (Ephemeral)

**Porque a sua sugestão deve ser adicionada na Loritta?**

Ninguém gosta de ver os erros no chat, nem a pessoa que ta usando, nem o resto do chat :D

**Considerações Finais**

Vc é muito boa no que vc faz

**Comment by MrPowerGamerBR** [comment]
Mas já é assim nos comandos via slash commands da Loritta.
