### ISSUE TITLE
Um bug dá loja do Fortnite

### ISSUE THREAD

**Issue by 165H** [LorittaBot/DreamLand#195]
1. A Loja do Fortnite quando notificou apareceu o "Premium" da Loritta
2. Infelizmente vocês vão tenque ir no discord.gg/fortnitebr-pt e pegar a foto que aparece em loja do dia

**Comment by MrPowerGamerBR** [comment]
> A Loja do Fortnite quando notificou apareceu o "Premium" da Loritta

É que está bugado a geração da loja em linguagens que não são português, eu preciso arrumar isso e ainda por cima atualizar o design da loja e colocar as novas seções que tem

**Comment by MrPowerGamerBR** [comment]
Duplicata de https://github.com/LorittaBot/DreamLand/issues/182
