### ISSUE TITLE
Comando de +avatar

### ISSUE THREAD

**Issue by ymarizinha** [LorittaBot/DreamLand#196]
**Qual é o problema?**

Antes, a uns 2 meses ou 3, quando eu dava o comando de +avatar em mim ou em alguém, a qualidade da imagem era boa, mas agora está meio ruim. Eu não sei se isso pode ser chamado de bug, mas tá me atrapalhando muito

**Como reproduzir o problema?**

1. Dar +avatar em alguém

**Comment by MrPowerGamerBR** [comment]
Bug do Discord, e não da Loritta
