### ISSUE TITLE
FALTA DE CRIATIVIDADE

### ISSUE THREAD

**Issue by Thalitaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa** [LorittaBot/DreamLand#20]
pelo amor de deus voces so colocam papeis de parede feios pra botar no perfil, mt falta de criatividade, uns bagui feio nada haver com nada foto de random, melhora isso ai credo

**Comment by MrPowerGamerBR** [comment]
Então mande imagens de qualidade boa que usem a licença CC BY-SA que eu coloco os backgrounds que você tanto fala que são bons que eu coloco como backgrounds.

**Comment by MrPowerGamerBR** [comment]
Como não enviou até agora eu irei fechar a issue
