### ISSUE TITLE
Consigo usar comandos mesmo banido.

### ISSUE THREAD

**Issue by Maykoon009** [LorittaBot/DreamLand#201]
**Qual é o problema?**
Nha, acho que o titulo e a descrição descrevem bem o problema, mas bem consigo usar comandos mesmo estando banido.

**Descrição maravilhosa sobre qual é o problema**
Eu fui banido de usar a Loritta, mas mesmo assim, posso usar comandos.

**Como reproduzir o problema?**
Ao invés de usar "+", utilize "/" (Comandos /) e o comando a frente. Assim, eu posso usar comandos mesmo banido da Loritta.

1. De novo?!
2. Estar banido; usar / ao invés do prefixo normal do bot; selecionar/escrever o comando; enviar a mensagem.
3. Esteja banido.
4. https://media.discordapp.net/attachments/879854467208589323/881001757885476945/unknown.png?width=886&height=498

**Considerações Finais**

Nha

**Comment by MrPowerGamerBR** [comment]
Duplicata de https://github.com/LorittaBot/DreamLand/issues/119
