### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Treifus** [LorittaBot/DreamLand#203]
Bug no comando +cocielochaves, imagem: https://media.discordapp.net/attachments/728843623306625035/882217548970610747/Screenshot_20210831-0757022.png

**Comment by MrPowerGamerBR** [comment]
Imagem quebrada, mas eu suponho que seja este bug: https://github.com/LorittaBot/DreamLand/issues/208 (e eu já arrumei o bug, yay!)
