### ISSUE TITLE
Não consigo resgatar sonho.

### ISSUE THREAD

**Issue by lucasjcruz** [LorittaBot/DreamLand#207]
**Qual é o problema?**

Bom, o problema em si não foi comigo, e sim com meu amigo. Mas como ele não quer reportar o bug, eu mesmo faço isso. O bug em si é ao se resgatar sonho no daily por conta do email dele (protonmail - https://pm.me), não é meio que uma questão de bug e sim uma forma de 'globalidade' dos emails.

**Como reproduzir o problema?**
 
1. Vocês devem criar uma conta no discord com um email do protonmail, e para conseguir encontrar o erro é só logar com essa conta (utilizando esse e-mail citado) e em seguida tentar pegar os sonhos no daily.

**Considerações Finais**

Caso queira mais informações sobre, me chame no Discord (Lukao#2798)
ou me mande um e-mail (lukaosrc@gmail.com)

Boa noite e bom serviço dev!

**Comment by MrPowerGamerBR** [comment]
Como é *muito* fácil criar uma conta no ProtonMail, a gente não permite usar ele, já que estavam usando o ProtonMail para farmar sonhos com contas alts.
