### ISSUE TITLE
BUG no comando cocielochaves

### ISSUE THREAD

**Issue by Kyun0r** [LorittaBot/DreamLand#208]
**Qual é o problema?**
BUG ao usar o comando "cocielochaves", 

**Como reproduzir o problema?**

1. Entre em algum servidor que a loritta esteja
2. Use o comando "cocielochaves"
3. Erro apresentado: " Premature end of Content-Length delimited message body (expected: 5,321,121; received: 2,307,776)"

Link da mensagem: https://cdn.discordapp.com/attachments/791404302887157791/883117329020489728/unknown.png

FOTO: ![lori](https://user-images.githubusercontent.com/68708488/131924774-cd1ed9b0-282d-4409-8b63-f1ba223da4fe.png)

**Comment by MrPowerGamerBR** [comment]
Foi corrigido no dia 04/09/2021: https://canary.discord.com/channels/297732013006389252/302976807135739916/883775335353708564

Era um bug que na verdade o sistema de gerar imagens estava levando MUITO tempo para gerar que o normal, enquanto comandos de imagens normais era raro acontecer esse erro, comandos de imagem que demoravam mais para serem processados davam esse erro.
