### ISSUE TITLE
Seria mt stonks

### ISSUE THREAD

**Issue by BernardoPC-Dev** [LorittaBot/DreamLand#21]
Seria mt stonks deixar a PerfectDreams de capital aberto e aitomatizar a compra de sonhos pelo website, sendo automático, tipo: Vc compra ai bota seu nick no discord, ai os sonhos automaticamente vão

**Comment by PeterStark000** [comment]
Não sei bem se essa foi a sua sugestão mas... 
Atualmente a compra de sonhos no website da Loritta já é possível e também funciona de maneira automática, você pode conferir valores e itens aqui -> https://loritta.website/user/@me/dashboard/bundles.
