### ISSUE TITLE
Eu não consigo pegar meus sonhos, isso ja faz dias, eu tento pegar mas fala ''Você já recebeu o seu prêmio diário hoje! Você poderá pegar novamente em 29 (ou 1 hora) minutos!'' eu tenho umas prints 

### ISSUE THREAD

**Issue by guetelindo** [LorittaBot/DreamLand#210]
não consigo pegar meus sonhos diarios, fica falando que eu ja peguei mas faz uns 7 dias que eu não pego

**Comment by MrPowerGamerBR** [comment]
Tem alguém que possui o mesmo IP que o seu pegando o daily antes de você.
