### ISSUE TITLE
O valor do ship editado não está funcionando no /ship

### ISSUE THREAD

**Issue by LeuuK** [LorittaBot/DreamLand#212]
O valor do ship editado não está funcionando
Para encontrar o tal bug é só editar o valor do ship e usar o ship com o / e um com o +
Tem prints a baixo (eu acho nunca usei o github)

**Comment by LeuuK** [comment]
Editar o valor do ship e testar com o + e o /

**Comment by LeuuK** [comment]
![Screenshot_20210904-235221](https://user-images.githubusercontent.com/90121572/132113432-68683d4d-89a4-488c-8a03-152e8157e8d4.png)

**Comment by hechfx** [comment]
Resolvido; Falta de atenção do usuário ao usar o comando.
