### ISSUE TITLE
Comando de banner

### ISSUE THREAD

**Issue by beckyvdd** [LorittaBot/DreamLand#218]
**Qual é a sua sugestão?**

Eu acho que deveria haver um comando parecido com o +avatar que funcione com banners, por exemplo +banner @{user} e a Loritta manda o banner do usuário

**Porque a sua sugestão deve ser adicionada na Loritta?**

Agora com a nova função de banner para quem tem Discord Nitro, seria útil ter esse comando para ver banners dos usuários.

**Comment by MrPowerGamerBR** [comment]
Já existe, `/user banner`
