### ISSUE TITLE
Max users emojifight

### ISSUE THREAD

**Issue by SrLuisKK** [LorittaBot/DreamLand#24]
No comando +emojifight bet, você ter a opção de escolher a quantidade de usuários que poderão entrar na rinha. Quando atingir essa quantidade, a rinha já iniciar, e ainda o autor da mensagem poderá iniciar quando quiser.
+emojifight bet (valor) (max_users)
+emojifight bet 2500 2

**Comment by joaoesteves10** [comment]
O comando já funciona assim.

**Comment by SrLuisKK** [comment]
> O comando já funciona assim.

ah, eu usei sem nenhum pra ver o que dava e não mencionava isso, de qualquer forma obrigado

**Comment by Nightdavisao** [comment]
Só para acrescentar a resposta do João.  
![Screenshot_20210418-200717_Discord.png](https://user-images.githubusercontent.com/33351880/115163829-b7371d80-a081-11eb-8561-aac254db5fe3.png)

**Comment by SrLuisKK** [comment]
eu fecho o issue ou deixo assim msm?

**Comment by Nightdavisao** [comment]
> eu fecho o issue ou deixo assim msm?

Vou fechar porque não tem porque deixar aberto
