### ISSUE TITLE
Embed no +atm

### ISSUE THREAD

**Issue by raaas5** [LorittaBot/DreamLand#255]
**Qual é a sua sugestão?**

Colocar a resposta do comando de +atm em um embed.

**Porque a sua sugestão deve ser adicionada na Loritta?**

Seria bom colocar em um embed para não marcar uma pessoa desnecessariamente apenas porque alguém está interessado em ver quantos sonhos a pessoa tem. Outro motivo é que mesmo que peguemos o ID da pessoa, a loritta marca a mesma de qualquer jeito.

**Comment by MrPowerGamerBR** [comment]
A versão em slash commands do comando (`/sonhos`) não menciona a pessoa, então isso não é mais um problema.

(Deixando mais claro: Ela menciona a pessoa mas ela não irá receber a notificação, como também você usar `/sonhos PessoaAqui` o Discord não menciona ela)
