### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by natsumdev** [LorittaBot/DreamLand#257]
**Qual é o problema?** sistema de /

Descrição maravilhosa sobre qual é o problema 

bom as pessoas que estiverem banido da loritta conseguiram usar o sistema do / no discord e fiquei sabendo que tu iria colocar todos os comandos no / isso significa que ngm nunca mais vai ficar banido da loritta, só vai parar de usar o site
**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!
bom tu já sabe
**Considerações Finais**

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
