### ISSUE TITLE
Bug de emojis - •Misael234•#3039

### ISSUE THREAD

**Issue by Misael2340** [LorittaBot/DreamLand#269]
**Qual é o problema?** 

Ao utilizar um comando "/" da loritta, no meu servidor, por algum motivos, os emojis ficam por extensivo/quebrados.

**Como reproduzir o problema?**

1. Por exemplo, o comando "/ship"

**Considerações Finais**

![image](https://user-images.githubusercontent.com/92757041/137800859-8ae95ee5-6163-4a77-b884-3ab33f369c6b.png)

**Comment by nonlyfx** [comment]
De nada
