### ISSUE TITLE
Comandos de Defesa para Invasões

### ISSUE THREAD

**Issue by MatteoFps** [LorittaBot/DreamLand#27]
**Qual é a sua sugestão?**

Adcionar comandos de lock e unlock só que para todos os chats, e de slowmode para todos os chats. Ou seja quando você usa esse determinado comando (lockall) você locka todos os chats, do mesmo jeito que você pode por slowmode em todos os chats com outro comando (slowmodeall).

**Porque a sua sugestão deve ser adicionada na Loritta?**

Isso ajudaria servidores que estão sofrendo de uma invasão por exemplo. Geralmente quando um servidor está sofrendo raid, você usa o comando +lock e bane os invasores, mas nesse meio tempo eles vão floodar e spammar em outros chats o que deixa mais difícil limpar todos os rastros de raids. Sem contar que podem ser usados para outras funções.

**Considerações Finais**

Então a minha sugestão é que criem 3 comandos, o de slowmode para todos os chats, o de lock para todos os chats, e o de unlock para todos os chats. Obrigado pela atenção.

**Comment by MrPowerGamerBR** [comment]
O problema de unlock de todos os chats é tentar evitar que canais de novidades & cia não sejam desbloqueados ao usar o comando.

**Comment by MatteoFps** [comment]
> O problema de unlock de todos os chats é tentar evitar que canais de novidades & cia não sejam desbloqueados ao usar o comando.

Faz sentido, obrigado por responder.

**Comment by MatteoFps** [comment]
> O problema de unlock de todos os chats é tentar evitar que canais de novidades & cia não sejam desbloqueados ao usar o comando.

Eu estava pensando, não existe alguma forma da Loritta guardar os chats que ELA bloqueou através do Registro de Auditoria? Isso poderia ajudar nesse problema, eu acho.

**Comment by MrPowerGamerBR** [comment]
> 
> 
> > O problema de unlock de todos os chats é tentar evitar que canais de novidades & cia não sejam desbloqueados ao usar o comando.
> 
> Eu estava pensando, não existe alguma forma da Loritta guardar os chats que ELA bloqueou através do Registro de Auditoria? Isso poderia ajudar nesse problema, eu acho.

Outro jeito seria guardar no banco de dados dela os canais que foram bloqueados por ela, se basear no registro de auditoria não é bom porque depois de um tempo (uns 30 dias? Não tenho certeza da data exata) as coisas do audit log somem.

**Comment by zLupa** [comment]
> > > O problema de unlock de todos os chats é tentar evitar que canais de novidades & cia não sejam desbloqueados ao usar o comando.
> > 
> > 
> > Eu estava pensando, não existe alguma forma da Loritta guardar os chats que ELA bloqueou através do Registro de Auditoria? Isso poderia ajudar nesse problema, eu acho.
> 
> Outro jeito seria guardar no banco de dados dela os canais que foram bloqueados por ela, se basear no registro de auditoria não é bom porque depois de um tempo (uns 30 dias? Não tenho certeza da data exata) as coisas do audit log somem.

Talvez seria melhor criar um cargo para cada servidor que usar o comando que negue todas permissões e adicionar em cada canal e guardar o ID desse cargo no banco de dados.
Na hora de dar `+unlock` pesquisar pelos canais com o ID do cargo e remover.
