### ISSUE TITLE
Bug que achei

### ISSUE THREAD

**Issue by Farofaofc** [LorittaBot/DreamLand#271]
**Qual é o problema?**

Oi equipe de suporte da lori, bem, recentemente como a Loritta está migrando para os Slash commands, pode ocorrer erros ou bugs. Bem, foi isso que aconteceu comigo, eu usei o shipp dos slash commands da Loritta, e aconteceu meio que um "erro" e fica do jeito da foto quando menciono as pessoas. Eu mencionei uma pessoa e outra porém ficou com a minha foto quando mencionei ela (Eu não me mencionei), fica tipo assim: <@id da pessoa> + <@id da outra pessoa> + Eu (sem eu ter me mencionado)

**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

![Screenshot 2021-10-22 09 29 51](https://user-images.githubusercontent.com/92989503/138455344-75b743cc-7471-4d17-aaf3-92fa1ac6db6d.png)

**Comment by MrPowerGamerBR** [comment]
Você mencionou as duas pessoas de forma errada na mensagem
