### ISSUE TITLE
não responde á nenhum dos comandos ( ex: +clean)

### ISSUE THREAD

**Issue by jamandadomato** [LorittaBot/DreamLand#274]
Ontem a Loritta respondia todos os comandos normalmente. Mas hoje eu entrei no servidor e quis apagar as mensagens de ontem com o comando +clean 100, e ela simplesmente não fez nada, enquanto os outros bots funcionam normalmente.

**Comment by MrPowerGamerBR** [comment]
Perguntas desse tipo devem ser feitas no servidor de suporte da Loritta
