### ISSUE TITLE
Um erro no emoji de xp da lori

### ISSUE THREAD

**Issue by adenilson0000** [LorittaBot/DreamLand#280]
**Qual é o problema?**

apenas um erro em um emoji na lori

**Como reproduzir o problema?**

No comando de sonhos do slash commands
Print: https://prnt.sc/1xmy3v9

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

**Comment by PeterStark000** [comment]
> Ela possui permissão para usar emojis externos? Pra mim funciona normalmente ![image](https://user-images.githubusercontent.com/76217874/139321272-6fc597c6-9a11-4d95-9b39-a0a5967de52c.png)

Provavelmente é um erro relacionado à essa permissão! Caso ela já tenha a permissão, verifique se a Loritta está no mesmo servidor que o emoji pertence!
