### ISSUE TITLE
Bug no UserInfo e RoleInfo

### ISSUE THREAD

**Issue by Luisin13** [LorittaBot/DreamLand#282]
**Qual é o problema?**
Comando no userinfo e roleinfo aparecem permissões bugadas

**Como reproduzir o problema?**

1. Utilize o +userinfo ou +roleinfo
2. Clique no emoji para ver as permissões caso seja o +userinfo
3. La estará o bug
![image](https://user-images.githubusercontent.com/84397555/139343303-5370079f-fa50-4049-9250-12df0ea8098c.png)
![image](https://user-images.githubusercontent.com/84397555/139343616-fe9e57cb-e80c-4f5e-89a6-40fdf6ca0b3d.png)

**Considerações Finais**
É um bug de escrita nas permissões do usuário ou cargo que algumas pessoas podem achar ruim

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...
![image](https://user-images.githubusercontent.com/84397555/139343723-1f9c5b72-160a-4273-b8cc-43d271daa56f.png)

**Comment by PeterStark000** [comment]
É um bug de locale, é por que o Discord adicionou novas permissões e portanto é necessário arrumar os arquivos de locale! Obrigado por reportar este bug!
