### ISSUE TITLE
Caracteres como "ç" dão erro ao adicionar como emoji

### ISSUE THREAD

**Issue by princessmortix** [LorittaBot/DreamLand#283]
### Qual é o problema?

Se usar "ç" para adicionar um emoji, o comando falha, como mostrado na print a seguir (sim, o server tem espaço suficiente para mais emojis).

### Como reproduzir o problema?

Adicione um emoji como algum nome que contenha o caractere "ç"
![image](https://user-images.githubusercontent.com/47502554/139504665-0c1f9d74-c0e8-4b0e-9357-48601c74e773.png)

### Considerações Finais

Imagino que já vi alguém reportando esse problema ou algo similar, porém não achei o issue.
ID do servidor, se necessário: `750138821017993298`

<img src="https://purr.objects-us-east-1.dream.io/i/img-20170715-wa0002.jpg" alt=catto> <caption style="text-align:right">Seu gato diario</caption>

**Comment by 165H** [comment]
Não dá pra adicionar um emoji com `ç` no discord, por isso não dá

**Comment by PeterStark000** [comment]
Isto é normal, é uma imposição colocada pelo próprio Discord!
