### ISSUE TITLE
Um erro de emoji

### ISSUE THREAD

**Issue by marcos-dionisio** [LorittaBot/DreamLand#284]
**Qual é o problema?**

Então, não sei se pode ser considerado um bug mas é que o emoji :error: da loritta é um emoji externo e quando tu desabilita emojis externos a mensagem sai com o nome do emoji.

![IMG_20211030_161235](https://user-images.githubusercontent.com/74318296/139557312-126426bf-517a-43ce-a709-c9d579332748.jpg)

**Como reproduzir o problema?**

1. Desative os emojis externos
2. Use o comando +ajuda

**Comment by DarkAngel5965** [comment]
Normal.
