### ISSUE TITLE
Filtração nas transações

### ISSUE THREAD

**Issue by AzureSky21** [LorittaBot/DreamLand#286]
**Qual é a sua sugestão?**

Filtrar as transações, por exemplo: `+transações <id> daily` `+transações <id> coinflip` `+transações <id> pay

**Porque a sua sugestão deve ser adicionada na Loritta?**
Pode facilitar na procura de alts no daily, facilitar em alguns casos na administração

**Comment by MrPowerGamerBR** [comment]
Adicionado (apenas disponível no novo `/transactions`) https://github.com/LorittaBot/Loritta/commit/a608d172b2c140dc70f5990c1525e3923bcd57c7
