### ISSUE TITLE
Bug no bloqueador de convites

### ISSUE THREAD

**Issue by thefelkybioons** [LorittaBot/DreamLand#295]
**Bug de menção no filtro de convites**

**Não sei se é um erro muito grande mas quando o usuário envia um convite no servidor o filtro avisa o usuário, mas antes disso a loritta marca um cargo específico creio eu que seja o maior cargo que você estiver no servidor, e pergunta se você não quer que esse tal cargo tenha permissão de mandar convites de outros servers no servidor.**

**Como reproduzir o problema?**

Ativando o filtro de bloqueador de convites no servidor. Quando ativa o filtro de bloquear convites, e a opção de avisar o usuário que é proibido

**Considerações Finais**

![Screenshot_20211112-165424](https://user-images.githubusercontent.com/73732144/141527759-06865d18-8220-429b-94f5-f920836f5242.png)

**Comment by PeterStark000** [comment]
Se eu não me engano ela manda essa mensagem quando o servidor tem o módulo ativo, porém nenhum outro cargo do servidor tem permissão para enviar invites no canal. Verifique se é isto mesmo! Caso não for, tente vir aqui ou no suporte e me mencione explicando a situação!
