### ISSUE TITLE
Server Xp por Voice

### ISSUE THREAD

**Issue by DominiqueCH** [LorittaBot/DreamLand#296]
**Qual é a sua sugestão?**

Poderia ser possível ter uma opção de ativar um modo da loritta adicionar XP aos membros que ficam em chamadas
Ex: Fulana fica em call e ainda assim recebe XP e pode subir de rank sem precisar interagir por chat

Como funcionaria?
Poderia ser uma opção ativável, mas se ativa-se seria obrigatório definir um chat para level up de calls, a cada minuto que a pessoa estivesse na call ela ganhasse uma certa quantidade de xp.
Para evitar afk farms deveria ser obrigatório também pra ativar a função definir uma chamada afk

**Porque a sua sugestão deve ser adicionada na Loritta?**

Muitas vezes exitem varios membros que não interagem muito em chat, mas para eles não ficarem fora do sistema de XP eles ainda poderiam subir de level assim fazendo que eles não perdessem disponibilidades que eles ganhariam chegado até certo rank.

**Considerações Finais**

Albedo vem pra casa por favor eu te amo seu lindo sou kinnier seu por favor vem pra casa

**Comment by PeterStark000** [comment]
Daria para fazer, mas não teria como verificar se a pessoa está realmente falando no canal, e sendo assim seria uma opção opcional.
