### ISSUE TITLE
Bug na função da utilização de comando inexistente.  

### ISSUE THREAD

**Issue by Bl4ckberry** [LorittaBot/DreamLand#297]
**Qual é o problema?**

Eu fui utilizar um comando da Lori mas acidentalmente escrevi errado (a função de comando inexistente tá habilitada nos servidores que eu costumo usar), porém o emoji e a penúltima frase do comando estavam com aquela função de "grifar" do Discord (não é o negrito) [`assim`].

**Como reproduzir o problema?**

Escrevendo alguma comando da lori incorretamente, no meu caso eu escrevi +broken ao invés de +broker.
![Screenshot_20211116-083440~2](https://user-images.githubusercontent.com/87507293/141982365-a269603e-84f5-4dbd-ad4f-c6ab493a9271.png)

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

https://user-images.githubusercontent.com/87507293/141982420-d84afc33-9e2c-47e5-9ce2-75fe9334fab4.mp4

Obrigada pela atenção <3.

**Comment by DarkAngel5965** [comment]
![image](https://user-images.githubusercontent.com/76217874/141990609-74667263-bbfc-4cd7-a7e6-b17bb6bd07d6.png)
realmente.

**Comment by PeterStark000** [comment]
O erro ainda é válido, mas creio que será desnecessário focar em arrumar isto por agora, pois futuramente a Loritta só utilizará Slash Commands, e Slashs já tem a lista oficial de comandos que podem ser utilizados ou não, portanto não faria sentido mudar isso no momento!
