### ISSUE TITLE
[BUG] Registro de auditoria

### ISSUE THREAD

**Issue by LourencoLolo** [LorittaBot/DreamLand#298]
**Qual é o problema?**

Registro de auditoria

**Como reproduzir o problema?**

1. Vá no [dashboard da Loritta](https://loritta.website/br/dashboard)
2. Vá no registro de auditoria

**Considerações Finais**

![image](https://user-images.githubusercontent.com/72362955/141996982-94b7c043-d647-4ab4-bd9a-e421ad71dbee.png)

**Comment by PeterStark000** [comment]
Issue duplicada, veja aqui a nossa reposta: https://github.com/LorittaBot/DreamLand/issues/59#issue-892103165
