### ISSUE TITLE
Action sendo traduzido como " açao " ao invés de ação

### ISSUE THREAD

**Issue by Stein0511** [LorittaBot/DreamLand#299]
**Qual é o problema?**

Não sei se isso é algo automático da Loritta, mas ela está traduzindo a palavra " action " com " açao " sem o " ~ "

**Como reproduzir o problema?**

Não sei colocar fotos, mas eu utilizei " +traduzir pt action " 
e só pra ver um negócio, usei "+traduzir en ação " ( que a princípio deu action corretamente )

**Considerações Finais**

N possuo uma consideração final, só acho que poderia dar uma olhada e mexer nisso ai tal...

**Comment by DarkAngel5965** [comment]
![image](https://user-images.githubusercontent.com/76217874/142400077-279fd8bd-b3cd-4c6e-bc02-1cf4489c7d89.png)
realmente isso acontece

**Comment by PeterStark000** [comment]
Isso não é um erro que podemos ajeitar, é um erro que existe na API que a Loritta utiliza para fazer as traduções. E acontece em outros bots que utilizam a mesma api, como vocês podem ver:
![image](https://user-images.githubusercontent.com/40671520/142488981-596d667f-28ff-43c7-92b9-5c3a3a298eaf.png)
