### ISSUE TITLE
Botão na lori

### ISSUE THREAD

**Issue by 165H** [LorittaBot/DreamLand#300]
Adicionar o botão “Add to server”, fica na aba “OAuth2”

**Considerações Finais**

Eu traduzi o site:

![](https://cdn.discordapp.com/attachments/897981030496104459/912501540940554311/IMG_3817.png)

**Comment by onlyfx** [comment]
Já tem.

**Comment by 165H** [comment]
> Já tem.

Agora tem, mas antes não tinha
