### ISSUE TITLE
Sobre o Coinflip

### ISSUE THREAD

**Issue by PedroXMD** [LorittaBot/DreamLand#308]
**Qual é a sua sugestão?**

Ser possível chamar varios coinflip usando apenas um comando, como por exemplo "+coinflip bet @....... 500k 5.
Ai quando os dois aceitassem aparecia apenas 1 mensagem que poderia ser essa "você ganhou 5 de 5 e lucrou 2.5kk!"
**Porque a sua sugestão deve ser adicionada na Loritta?**
Evitaria o flood, principal em server com muitas pessoas. As pessoas usam o Coinflip e ficam editando a msg até chegar na quantidade que quer, mas isso em servidor grande vira um flood gigantesco e isso resolveria o problema e ficaria super mais fácil!

**Comment by DarkAngel5965** [comment]
Não seria mais fácil colocar a quantia toda (no caso, 2.5kk) de uma única vez?

**Comment by MrPowerGamerBR** [comment]
Eu concordo com o @DarkAngel5965: Isso seria inútil, é só colocar a quantidade que você deseja apostar de uma vez em vez de ficar colocando quantidades pequenas até chegar em quanto você deseja.
