### ISSUE TITLE
Oráculo do amor bugadasso

### ISSUE THREAD

**Issue by SKdaOLMP** [LorittaBot/DreamLand#311]
**Qual é o problema?**

Oráculo tá brigando sempre que vou editar os valores do ship 

Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

Só entrar no site da Lori e tentar usar o oráculo que buga
Aí vai aparecer essa mensagem
{"error":{"code":703,"reason":"Unknown User","help":"https://loritta.website/docs/api"}}
**Considerações Finais**

Por favor conserta pra eu conquistar minha crush 😔

**Comment by DarkAngel5965** [comment]
Como no próprio erro diz, "Usuário Desconhecido", você deve ter colocado o id/tag de um usuário desconhecido. Se não for isso, aí eu não sei.

**Comment by MrPowerGamerBR** [comment]
Duplicata: https://github.com/LorittaBot/DreamLand/issues/248
