### ISSUE TITLE
Colocar banner e avatar de servidor nos comandos `+avatar` e `/user banner`, assim os usuários poderão ver seu avatar e banner de servidor.

### ISSUE THREAD

**Issue by AquillesdaAmizade** [LorittaBot/DreamLand#312]
**Qual é a sua sugestão?**

Sugestão incrível maravilhosa chocante que vai arrebentar o mundo...

**Porque a sua sugestão deve ser adicionada na Loritta?**

Texto texto texto texto texto...

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

**Comment by MrPowerGamerBR** [comment]
Ainda não está pronto
![DiscordCanary_XjPuTB2KVu](https://user-images.githubusercontent.com/9496359/159592889-86f96f70-682d-45f2-8a30-03e201c54625.gif)

**Comment by MrPowerGamerBR** [comment]
Como não é possível pegar o banner do usuário em um servidor (sad), então a sugestão já está implementada!
