### ISSUE TITLE
Acho que encontrei um bug no coinflip

### ISSUE THREAD

**Issue by leovlund** [LorittaBot/DreamLand#313]
Basicamente, tem uma forma de sempre ganhar o coinflip bet.

Sempre que um dos participantes faz uma aposta de 200 sonhos e você ganha, vc irá perder a aposta que você fizer com ele depois.

**Como reproduzir o problema?**

1. Aposte 200 sonhos com alguém no coinflip bet até a outra pessoa ganhar
2. Quando a pessoa ganhar, faça em seguida uma aposta de qualquer valor que quiser (testamos com 12k, 25k, 30k, 35k etc)
3. Você irá ganhar a aposta grande

Aqui vão alguns exemplos:

![99517ADB-7D9C-4D21-86D1-6B538AC65120](https://user-images.githubusercontent.com/64642550/146571937-d782f442-c907-45dd-9f1a-1f38416b5b24.png)
![39E35928-445F-4E5A-BB1B-245E18803B2F](https://user-images.githubusercontent.com/64642550/146571948-ad6561c7-3953-4311-87cb-2d186f8d07ea.png)
![2BE26B6D-7039-455D-9849-9FF8B5EF674D](https://user-images.githubusercontent.com/64642550/146571954-eeab54d0-e32f-45b5-8042-2b1ce8b3fe0d.png)
![558835F9-33E0-48D6-9FEC-9AD706783530](https://user-images.githubusercontent.com/64642550/146571960-979b4b61-245e-477e-ab01-3cb2e8db4369.png)
![0AC97D80-6608-4E48-83A6-9A802DE135B1](https://user-images.githubusercontent.com/64642550/146571963-10e821e3-fe13-438c-8466-e9248b65daf1.png)
![AE18C2D2-3EFC-4CA5-8B82-4CC3F64A3602](https://user-images.githubusercontent.com/64642550/146571972-00a06324-8978-40ab-8b77-04585a1cc2e0.png)
![2DBEA367-70EC-440F-BC6C-2A6293FEF216](https://user-images.githubusercontent.com/64642550/146571977-6e040e9d-82a5-429c-8391-67311fbac88d.png)
![0BFAC618-A685-4624-B979-DF27E1B92F95](https://user-images.githubusercontent.com/64642550/146571980-a23b74ac-11ed-4bfd-8db3-caef8ead8101.png)
![A24CB29E-F933-41C5-A61F-445C3067C0F6](https://user-images.githubusercontent.com/64642550/146571987-2741298b-01ca-4b97-bc72-eebe7e8a9e68.png)
![885AC30E-F8C3-4335-8ADA-18DFD85406DA](https://user-images.githubusercontent.com/64642550/146571989-0dbf5bc2-adc3-46a8-8a95-47da7736bffd.png)

**Comment by DarkAngel5965** [comment]
Não existe bug do coinflip. O coinflip funciona através de probabilidades.

**Comment by DanielaGC** [comment]
Como o DarkAngel já disse, não existe bug do coinflip, eu recomendo que você assista este vídeo pra entender como funciona a questão de probabilidade https://youtu.be/eFyAyz6Xy6g
