### ISSUE TITLE
Reaction Roles

### ISSUE THREAD

**Issue by EduardoDudys** [LorittaBot/DreamLand#315]
## LEVEM EM NOTA: 
Sei que [Reaction Roles](https://support.discord.com/hc/pt-br/articles/1500012528941-Pronoun-Picker-Bot-FAQ#h_01F6T8AWQMJMRQXD58MNGN107V) já esta dentro dos planos do Discord, mas o bot que eles deixaram para traz não é totalmente configurável, até eles levarem esse projeto adiante, a Loritta tem uma chance de conseguir fazer algo mais maleável.

## Qual é a minha sugestão?
Eu sou alguem que vem usando a Lorrita em servidores (quase) diariamente e tem uma coisa que eu e muitos sentem falta é reaction roles (dar cargo ao dar react em certo emoji). A Loritta é um bot incrivel pra entretenimento quanto moderação com uma variedade de comandos diferentes, por mim eu teria um servidor inteiro SÓ com a Loritta, mas tem certas coisas que eu sinto falta em ter é Reaction Roles para dar cargos de pronomes ou cargos de notificações pra quem não gosta de levar @everyone.

## Porque a sua sugestão deve ser adicionada na Loritta?
Eu adoro a miscelânea de níveis por experiência, autorole e o contador de membros, ter algo como reaction roles seria como colocar a cereja no bolo, perfeito. 

## Considerações Finais
Caso essa sugestão tome um futuro adiante, tem certas coisas que seria bom deixar em mente:

- Seria bom conseguir configurar os Reaction Roles pelo website da Loritta (eu sei que isso é obvio).
- Ser opcional criar um embed ou texto pelo proprio website ou usar uma mensagem já escrita por alguem.
^^ Isso é importante, bots como MEE6 ou Dyno criam a propria mensagem para os reaction roles, eles não dão a opção de usar uma mensagem já escrita por alguem.
- Ser opcional a Loritta mandar mensagem para o user avisando quando ele pegou o cargo e quando ela tirou.
^^ Outra coisa importante, é chato ficar recebendo DM avisando se você pegou o cargo ou não, seria bom ser uma ação silenciosa.

![image](https://user-images.githubusercontent.com/80128992/147311527-c490455d-20e6-4b1a-a956-d2b5c7692fb7.png)

**Comment by DaviidHere** [comment]
Gostei da sugestão. Concordo principalmente com a parte de ser opcional a Loritta mandar mensagem para o user, já que pode acabar spammando a inbox do usuário.

**Comment by DarkAngel5965** [comment]
já vai ser adicionado #17

**Comment by EduardoDudys** [comment]
pode cre
