### ISSUE TITLE
Minha sugestão ^^

### ISSUE THREAD

**Issue by Linnuye** [LorittaBot/DreamLand#319]
**Qual é a sua sugestão?**
Eu Sugiro Francamente, Que tenha um sistema de AutoWarn (Quando alguém enviar uma certa mensagem, O Bot Automaticamente Punir) **EXEMPLO** 
Mlk: Enter this link to get nitru https://rickroll.com 
Loritta: Bye Bye! -bane-

**Porque a sua sugestão deve ser adicionada na Loritta?** 
Porquê é Útil. Só olhar pro bate papo que tu entende do q eu tô falando. A cada 20 minutos uma pessoa é hackeada, E ela vai hackear outros, com um link.
Apartir de aqui não tenho que explicar, é auto-explicativo.

**Considerações Finais**
Isso ajuda aos Guarda costas da Lori n perderem o tempo, e tbm ajuda outros sv.

-------------
[https://m.youtube.com/watch?v=nl5isYGEhig](url) porquê não deixar uma música pra glr escutar?

**Comment by onlyfx** [comment]
https://github.com/LorittaBot/DreamLand/issues/17#issuecomment-821993340
