### ISSUE TITLE
Remoção do comando +vemdezap

### ISSUE THREAD

**Issue by zRisee** [LorittaBot/DreamLand#32]
**Qual é a sua sugestão?**

Remoção do comando +vemdezap 

**Por que sua sugestão deveria ser aceita?**

Porque muitas pessoas abusam desse comando utilizando: `+vemdezap (servidor do membro)`. Isso prejudica bastante o servidor da pessoa que isso ocorrera.

**Comment by Pedrinho268** [comment]
só desativar o comando

**Comment by MrPowerGamerBR** [comment]
O bug de poder mencionar coisas com o `+vemdezap` foi corrigido (ela apenas remove a menção) e a nova versão do Vem de Zap `/text vemdezap` não notifica pessoas mencionadas. :tada:
