### ISSUE TITLE
O site está dando erro

### ISSUE THREAD

**Issue by ZombieGangster** [LorittaBot/DreamLand#324]
**Qual é o problema?**

Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...
![Screenshot_2022-01-17-20-06-17-278_com android chrome](https://user-images.githubusercontent.com/97922510/149846766-beca88e4-4eab-44eb-96d6-77c0f9bccee4.jpg)

**Comment by MrPowerGamerBR** [comment]
Provavelmente a Loritta estava instável na hora que você acessou o website
