### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by medusa023** [LorittaBot/DreamLand#327]
![Screenshot_20220126-085349](https://user-images.githubusercontent.com/98462917/151160408-257c7ab2-c3a6-4b7b-a321-c7b6cf036eed.png)

**Qual é o problema?**

Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...
Olha, eu coloquei la o /bet coinflipglobal né. Coloquei o valor 2500 (2.5k) ai falou pra eu pegar daily e falou que eu não tinha o valor de 2500 sonhos sendo que eu tinha 4900 sonhos. E ainda faltava 15 horas para o próximo daily, então disse que eu não tinha o valor mesmo tendo. E pegar daily faltando 15 horas pro proximo. Espero que entenda. Vou deixar a seguir os prints ai..... 
.
![Screenshot_20220126-085349](https://user-images.githubusercontent.com/98462917/151160509-0e945bde-69f1-4ea7-bcf8-c9bf817204f4.png)
.
![Screenshot_20220126-085341](https://user-images.githubusercontent.com/98462917/151160563-7428d825-0074-44f8-a7dc-8df556745268.png)

**Comment by MrPowerGamerBR** [comment]
Você colocou para apostar pela Loritta Canary, e não pela Loritta normal. Você não tem sonhos suficientes na Loritta Canary.
