### ISSUE TITLE
Bug no /ship

### ISSUE THREAD

**Issue by Pokeywo** [LorittaBot/DreamLand#328]
**Qual é o problema?**

Está bugado os Emojis

**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...
![Screenshot_20220128-173339](https://user-images.githubusercontent.com/97060562/151617969-8f3a0d2a-6ef9-496a-81a1-6f87439d859f.png)

**Comment by zolinhoo** [comment]
Que

**Comment by MrPowerGamerBR** [comment]
1. Você mencionou os usuários incorretamente
2. Os emojis não funcionam pois você não deu permissão de "Usar emojis externos" para `@everyone` (Sim, precisa ser para `@everyone`)

**Comment by SrSpiderGamer** [comment]
Me dá unban pvf Gaby😘#0001 eu usei a foto igual a sua foto.

Em qua, 23 de mar de 2022 16:08, MrPowerGamerBR ***@***.***>
escreveu:
