### ISSUE TITLE
Adicionar o Comando +sex

### ISSUE THREAD

**Issue by OFehEGostoso** [LorittaBot/DreamLand#332]
**Sugestão:**
- adicionar o comando +sex na loritta, ele sera apenas permitido ser usado em canais nsfw
———————-
**Porque deveria ser adicionar:**
As vezes os casais, ou pessoas que se gostam e não tão namorando querem fazer. Isso na brotheragem tlgd por favor adicione
————————
**Consideracao final**
- O feh eh gostoso

**Comment by OFehEGostoso** [comment]
Adicionem logo, não vou deixar ngm questionar, apenas adicionem

**Comment by zolinhoo** [comment]
?

**Comment by DarkAngel5965** [comment]
Irmão, por que caralhos o power adicionaria um comando de sexo? Se procura isso, pesquisa no google.
