### ISSUE TITLE
Mudar as permissões de +avatar

### ISSUE THREAD

**Issue by Lightt10** [LorittaBot/DreamLand#335]
**Qual é a sua sugestão?**
Criar uma função no site para as pessoas nao deixarem outros membros pegarem a sua foto de avatar
**Porque a sua sugestão deve ser adicionada na Loritta?**

Algumas pessoas nao gostam que peguem sua foto de perfil

**Comment by Lightt10** [comment]
> 

Tem poucos bots com esse comando e um que ta mais presente nos severs é a loritta

**Comment by MrPowerGamerBR** [comment]
Eu não acho que isso deveria ser implementado pois existem outros jeitos de pegar o avatar de alguém mesmo sem a Loritta, sendo eles:
* Outros comandos de outros bots
* Usando inspecionar elemento pelo seu navegador ou pelo Discord
