### ISSUE TITLE
Userinfo

### ISSUE THREAD

**Issue by Valeria-h** [LorittaBot/DreamLand#340]
**Qual é a sua sugestão?**

Exibir a quantidade de boost dados por alguém no +userinfo

**Porque a sua sugestão deve ser adicionada na Loritta?**

É uma informação útil

**Comment by MrPowerGamerBR** [comment]
Infelizmente isso é impossível pois o Discord não dá essa informação para bots, só dá para saber se a pessoa deu boost no servidor e quando ela deu o primeiro boost. :(
