### ISSUE TITLE
+info lembrete

### ISSUE THREAD

**Issue by godavida** [LorittaBot/DreamLand#38]
**Qual é a sua sugestão?**

Lembra do que agente lembro Para Agente sabe, quando tempo falta E quando Tempo pode Demora!

**Porque a sua sugestão deve ser adicionada na Loritta?**

Para Si Torna Uma Coisa pra facilitar Aquelas pessoas que não lembram

**Considerações Finais**

te amo Loritta

**Comment by Pedrinho268** [comment]
Tem o "+lembrete list"  Pra isso 👍🏻
