### ISSUE TITLE
Meme template 

### ISSUE THREAD

**Issue by AzureSky21** [LorittaBot/DreamLand#42]
Fazer um comando desse template aqui ó: https://youtu.be/x7RYYtYK5Cw
![IMG_20210427_191851](https://user-images.githubusercontent.com/54769777/116319762-792aaf80-a78d-11eb-9962-6190838fa671.jpg)

**Comment by MrPowerGamerBR** [comment]
https://user-images.githubusercontent.com/9496359/116341321-0c2c0f80-a7b7-11eb-806e-b82c7b328fc6.mp4
