### ISSUE TITLE
Comando +spolier

### ISSUE THREAD

**Issue by Oseuamiguinhu** [LorittaBot/DreamLand#48]
**Qual é a sua sugestão?**
Ela é de um comando +spolier para caso você mande uma imagem a lorrita manda a mesma imagem só que com spolier.

**Porque a sua sugestão deve ser adicionada na Loritta?**
As vezes quando você usa o discord pelo celular e quer mandar uma imagem com spolier e muito chato ter que ficar renomeando o nome do arquivo para a imagem, seria bom um comando desses.

**Comment by PeterStark000** [comment]
Eu acho que talvez seja desnecessário por que de qualquer forma pra usar o comando a pessoa vai ter que mandar a imagem no chat, além do que, futuramente o Discord deve implementar uma maneira de marcar spoiler no mobile.
