### ISSUE TITLE
Poder configurar o tema do website da loritta

### ISSUE THREAD

**Issue by Oay54** [LorittaBot/DreamLand#53]
**Qual é a sua sugestão?**

Poder configurar o tema do website da loritta. 

**Porque a sua sugestão deve ser adicionada na Loritta?**

Assim como no google, tmb acharia legal poder configurar as cores como colocar tema negro ou outros temas, configurar interface como por exemplo: poder configurar para a barra azul de cima para ficar em baixo, lado e etc... Ou até mesmo poder mudar a cor de algumas coisas do site.
Assim a pessoa configura o site da forma que ele achar melhor e agradável para ele.

**Comment by MrPowerGamerBR** [comment]
Já existe um tema escuro no website, só clicar no botãozinho de "Lua" que tem na navbar (Mas deveria ter em um lugar mais acessível já que muita gente não sabe)
