### ISSUE TITLE
Sugestão para a Loritta

### ISSUE THREAD

**Issue by arttuty** [LorittaBot/DreamLand#57]
Queria que vocês adicionassem uma forma da Loritta deletar a mensagem de bem-vindo quando um usuário sair em menos de tais horas. Não sei se é contra as limitações do Discord, mas acharia legal se fizessem isso. Obrigado.

**Comment by DavidMendes0123** [comment]
Olá!
Bom, minha sugestão era criar um comando de "userbanner", já que temos essa nova função para quem tem nitro poder escolher a faixa do perfil, aí poderia criar um comando desse tipo, já que existe os comandos de +avatar, +servericon entre outros, não sei se essa sugestao pode ser útil, mas tá aí.

**Comment by joaoesteves10** [comment]
#81
