### ISSUE TITLE
Ctrl c + Ctrl v no bom dia e cia

### ISSUE THREAD

**Issue by Oseuamiguinhu** [LorittaBot/DreamLand#60]
**Qual é o problema?**

Conseguir dar ctrl c + ctrl v no bom dia e cia
**Como reproduzir o problema?**
Quando a lorrita mandar a mensagem sobre o bom dia e cia, tirar uma captura de tela do texto  (mais facilmente no pc) dar +ocr e copiar o texto, as vezes o texto vem com alguns erros de ortografia no +OCR

**Comment by MrPowerGamerBR** [comment]
Isso é impossível de ser corrigido, mesmo se bloquear no `+ocr` da Loritta, outros bots tem comandos que fazem as mesmas coisas.
