### ISSUE TITLE
Melhorar msg de boas vindas no pv

### ISSUE THREAD

**Issue by BernardoPC-Dev** [LorittaBot/DreamLand#62]
Inves da lori mandar um texto enorme falando q n foi ela q escreveu a msg, podia só botar tipo "Msg escrita por fulano (id) e n vinculada a Loritta" ou "Ass: Fulano (id)", pq aqla msg ENORME estraga uma msg q na maioria das vzs é curta, eu n to falando pra tirar, so p melhorar como eu disse por ex, pode ser uma boa

**Comment by joaoesteves10** [comment]
O objetivo da mensagem é evitar confusões sobre possíveis mensagens de boas vindas inadequadas, logo é necessário que ela seja clara e explique corretamente e de forma inequívoca porque foi enviada, por quem, e o que fazer caso seja inapropriada, o que acreditamos que a mensagem atual faz melhor do que um ``"Ass: Fulano (id)"``, que só toca em um dos pontos abordados acima. Assim, fecharei a issue até recebermos um texto que cumpra os requisitos acima de forma mais satisfatória do que o atual.
