### ISSUE TITLE
bug com webhook

### ISSUE THREAD

**Issue by Misatokk** [LorittaBot/DreamLand#66]
Bom dia, boa noite, boa tarde.

Ontem vi um ataque ao servidor no qual frequento utilizando o comando do Faustão, não sei se é uma falha mas acredito que seja da Loritta. Não tinha outros bot com comandos brasileiros apenas ela. 
     Conforme a print, o mlk conseguiu marcar everyone e conversar normalmente como um +say. Não sei se é um bug da Loritta, só vim ver se já aconteceu com outras pessoas.
![Screenshot_20210517-062848](https://user-images.githubusercontent.com/84300517/118427102-d9cd4e00-b6a2-11eb-80d9-c17f425f5ad8.png)

**Comment by Pedrinho268** [comment]
bem isso não é bug da loritta, alguém conseguiu a url do webhook e pode ter ficado mandando isso.

**Comment by MrPowerGamerBR** [comment]
Não é um bug, você que deveria escolher pessoas melhores para a sua equipe antes de colocar a culpa na Loritta.
