### ISSUE TITLE
Votos Repetidos

### ISSUE THREAD

**Issue by ySnoopyDogy** [LorittaBot/DreamLand#67]
**Qual é o problema?**

Os votos estão sendo computados mais de uma vez. Aconteceu só uma vez comigo até agora, mas é preocupante pois um voto meu no top,gg contou 3 vezes, um a cada minuto

**Como reproduzir o problema?**

1. Votar na Loririn no Top.gg (Foi literalmente so isso que eu fiz)

**Considerações Finais**

Eu n sei como foi o bug, não sei se isso é uma issue válida, e também não sei se já é de conhecimento de vocês isso, mas é algo meio :( já que ela contabilizou votos a mais. Ela contou 3 votos, um a cada minuto, printzin abaixo 
![image](https://user-images.githubusercontent.com/59155752/118502371-05325600-b700-11eb-968f-50362c659724.png)

**Comment by MrPowerGamerBR** [comment]
Isso foi corrigido e alterado para tentar evitar esses problemas do top.gg
