### ISSUE TITLE
Bug na +raspadinha comprar

### ISSUE THREAD

**Issue by gustavoske** [LorittaBot/DreamLand#72]
**Qual é o problema?**
Quando uso a raspadinha,não consigo ver todos os emojis, só consigo ver alguns,alguns spoilers não abrem.
Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

Bem,não sei se é só comigo,eu só uso +raspadinha comprar,e n consigo olhar todos emojos

**Considerações Finais**

![download (24)](https://user-images.githubusercontent.com/84347101/119061188-261dd400-b9aa-11eb-8268-1f1d7436eed0.jpeg)

**Comment by DarkAngel5965** [comment]
Você usa esse comando no mobile, @gustavoske? Se for no mobile, é difícil mesmo abrir os spoilers da raspadinha.

**Comment by joaoesteves10** [comment]
Seja ou não mobile, trata-se de um problema com o client do Discord e não da Loritta em si, pelo que fecharei a issue.
