### ISSUE TITLE
+sonhos top bugado

### ISSUE THREAD

**Issue by GiikiNOTFound** [LorittaBot/DreamLand#75]
**Qual é o problema?**

+sonhos top bugado

Descrição:

quando tento executar o sonhos top a loritta retorna um erro

**Como reproduzir o problema?**

digite +sonhos top, e ela ira retornar um erro, image must not be null

![unknown](https://user-images.githubusercontent.com/45574749/119208130-26d06c00-ba77-11eb-91f7-71feaf5e6489.png)

**Comment by DarkAngel5965** [comment]
Para mim o comando funciona perfeitamente.

**Comment by GiikiNOTFound** [comment]
q estranho, pra mim deu esse erro ae

**Comment by GiikiNOTFound** [comment]
mas agr n ta dando mais
