### ISSUE TITLE
Um Comando Lock All

### ISSUE THREAD

**Issue by Wolfy-sp** [LorittaBot/DreamLand#78]
**Qual é a sua sugestão?**

A Sugestão é sobre um Comando derivado/Originado do Lock , que é aquele que faz o chat ser fechado, para Ninguém falar Nele, Estou falando se de alguma Maneira Houvesse um Lock All
**Porque a sua sugestão deve ser adicionada na Loritta?**

Esse Comando Seria Para Fechar todos os Canais de Chat daquele Servidor que o bot está sendo usado no Momento
Tipo, Isso Evitaria de ficar fechando chats de um por um, com Servidores grandes de mais de 100 chats

**Considerações Finais**

Essa seria minha sugestão, Pois a varios servidores, que tem problemas com esse tipo de comando, uns exemplos claro
Aqueles Servidores que estão fazendo de tudo para dar certo e ainda não tem staff otima no momento que é preciso...

**Comment by MrPowerGamerBR** [comment]
Duplicata: https://github.com/LorittaBot/DreamLand/issues/27
