### ISSUE TITLE
Emoji não carrega

### ISSUE THREAD

**Issue by vitu1928** [LorittaBot/DreamLand#80]
**Qual é o problema?**

Emoji não carrega.

**Como reproduzir o problema?**
Executar o comando 

**Considerações Finais**
![image](https://user-images.githubusercontent.com/58984150/119423680-3996ab00-bcda-11eb-862a-b7b7be46a826.png)

**Comment by DarkAngel5965** [comment]
A loritta tem permissão para usar emojis externos? O problema pode ser esse.

**Comment by vitu1928** [comment]
> A loritta tem permissão para usar emojis externos? O problema pode ser esse.

Sim!!! Eu fui me dar conta disso e já vim aqui fechar o caso, valeu.
