### ISSUE TITLE
(BUG) Emojis personalizados em comandos

### ISSUE THREAD

**Issue by HeyyCzer** [LorittaBot/DreamLand#82]
**Qual é o problema?**
Ao utilizar Slashcommands (/cancelled), por exemplo, os emojis personalizados ficam como texto na mensagem.

**Como reproduzir o problema?**
1. Usar Slashcommands, aparentemente.
2. Quando a Lori responde, os emotes ficam :emote:
![Demonstração](https://user-images.githubusercontent.com/43618377/119503875-cde82880-bd41-11eb-92bb-5c628f53483f.png)

**Comment by vitu1928** [comment]
Precisa permitir que ela possa enviar emojis externos!! Eu cometi o mesmo erro..

**Comment by HeyyCzer** [comment]
> Precisa permitir que ela possa enviar emojis externos!! Eu cometi o mesmo erro..
Loritta com permissão de Administrador no servidor.

**Comment by MrPowerGamerBR** [comment]
@HeyyCzer com slash commands, `@everyone` precisa ter permissão para usar emojis externos para funcionar, é uma limitação do Discord.
