### ISSUE TITLE
Loritta não manda o emoji certo na embed de upar level

### ISSUE THREAD

**Issue by andreasgrum00** [LorittaBot/DreamLand#83]
![image](https://user-images.githubusercontent.com/55033182/119531441-4b1f9780-bd5a-11eb-9589-c7fc4ac48ed3.png)

Quando alguém upa de Level em algum server e a Lori manda embed, não aparece o emoji :i_reallylikecoffee:

**Comment by MrPowerGamerBR** [comment]
Como você colocou o emoji na configuração da Loritta?

**Comment by uziel-sla** [comment]
Se eu não me engano você tem que colocar o emoji no formato da API Discord (<:nomeDoEmoji:idDoEmoji> para emojis comuns e para emojis animados <a:nomeDoEmoji:idDoEmoji>), e para conseguir o emoji neste formato basta colocar uma barra invertida (`\`) antes dele e no celular colocar entre `crases`

Ou o emoji é externo e a Loritta tá sem permissão de usar emoji externo no seu servidor

**Comment by andreasgrum00** [comment]
> Se eu não me engano você tem que colocar o emoji no formato da API Discord (<:nomeDoEmoji:idDoEmoji> para emojis comuns e para emojis animados <a:nomeDoEmoji:idDoEmoji>), e para conseguir o emoji neste formato basta colocar uma barra invertida (`\`) antes dele e no celular colocar entre `crases`
> 
> Ou o emoji é externo e a Loritta tá sem permissão de usar emoji externo no seu servidor

Consegui resolver, obg msm!
