### ISSUE TITLE
Bug do userinfo e serverinfo

### ISSUE THREAD

**Issue by KachuApenas** [LorittaBot/DreamLand#89]
**Qual é o problema?**

Quando eu uso o comando de userinfo, aparece a mesma data em que o servidor foi criado, testei na minha conta de 10 dias, e na outra de 1 ano, o problema foi o mesmo

**Como reproduzir o problema?**

1. Descreva aqui
2. Quais passos a gente precisa fazer
3. Para conseguir encontrar o bug
4. Se quiser, pode colocar fotos!
Nao consegui mandar a print, mas qualuqer coisa, aqui está meu @ do discord: Kachu, Apenas😳#0877

**Comment by MrPowerGamerBR** [comment]
Não estou vendo o problema, neste exemplo o horário é o mesmo pois eu que sou o dono do servidor

![image](https://user-images.githubusercontent.com/9496359/120054352-e25c4780-c005-11eb-8261-6fc559542943.png)

**Comment by MrPowerGamerBR** [comment]
Seria bom você mandar algumas fotos do que a Loritta responde quando você usa o `+userinfo` e o `+serverinfo`
