### ISSUE TITLE
"bug" no +pay 

### ISSUE THREAD

**Issue by Madarz777** [LorittaBot/DreamLand#91]
**erro de digitação no +pay **

![IMG_20210529_115620](https://user-images.githubusercontent.com/85027163/120074912-787b8680-c075-11eb-9ba5-ae4abd9c43c4.jpg)

1. colocar a Lori em inglês
2. usar +pay com um valor acima do que você tem
3. eu testei outras vezes pra confirmar, e as vezes não tinha erro, mas a Loritta falava em português (mesmo eu usando em inglês)
4. acho q é só isso mesmo :)

**Comment by joaoesteves10** [comment]
[Resolvido!](https://github.com/LorittaBot/LorittaLocales/commit/94209cb72d701c9f77ac2307a5782285c52bb68a)
