### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by yunno-do-grau** [LorittaBot/DreamLand#95]
eu joguei na rifa e ganhei 2milhões , ai eu fui ver em que top do global eu tava mas eu coloquei e vi que eu estava no top 91, mas no comando "+bal" ou "+atm" tava dizendo que eu estava no top 454 
![bug](https://user-images.githubusercontent.com/85058189/120099845-1cb40a80-c114-11eb-89a6-8140dad9a4c2.png)

**Comment by MrPowerGamerBR** [comment]
Cinco usuários aparecem por página no `+sonhos top`, você aparece na página 91.

Logo a sua posição aparece entre `90 * 5` e `91 * 5`, ou seja, `450` e `455`.

Não é um bug, a Loritta só está mostrando no comando de `+sonhos` a sua posição geral enquanto o argumento do `+sonhos top` você usa a página que você deseja ver.
