### ISSUE TITLE
Loritta Cache

### ISSUE THREAD

**Issue by NeonFlyZ** [LorittaBot/DreamLand#96]
A Loritta poderia ter um micro-servidor com cache de usuários.
Caso alguém usar comandos como o `+userinfo` ou outros, este cache iria retornar informações do usuário já salvas, em vez de fazer com que a loritta tenha que pedir informações para o discord.
Cada cluster teria seu próprio cache de usuários, e caso informações do usuário mudarem, a loritta iria receber o evento na gateway e já alterar os dados no cache
Seria util para ela não tomar rate limit quando muitas pessoas tentarem usar comandos ou funções que dependam do nome de usuários.

**Comment by MrPowerGamerBR** [comment]
> Cada cluster teria seu próprio cache de usuários, e caso informações do usuário mudarem, a loritta iria receber o evento na gateway e já alterar os dados no cache

A Loritta literalmente já funciona desse jeito como também guarda dados de usuários no banco de dados para quando não precisar acessar a API do Discord sempre.
