### ISSUE TITLE
Minecraft Head Avatar

### ISSUE THREAD

**Issue by Polar8Bits** [LorittaBot/DreamLand#97]
Um comando que gere uma imagem direta da cabeça de um player

+mcavatar Nick

Pra agilizar o processo, esse site disponibiliza avatar
https://mc-heads.net/avatar/Nick/1000
(O 1000 é a resolução)

**Comment by MrPowerGamerBR** [comment]
Já existe o `+mcavatar` e ele faz exatamente o que a sua sugestão diz

![image](https://user-images.githubusercontent.com/9496359/120206588-c3c2a000-c201-11eb-9a32-8af9ac909b3d.png)
