### ISSUE TITLE
Notificação de Unban

### ISSUE THREAD

**Issue by NextRage** [LorittaBot/DreamLand#98]
**Qual é a sua sugestão?**

Fazer com que a Lori envie uma mensagem de unban quando você é desbanido de algum servidor, assim a Lori iria te notificar caso ela tenha outros servidores em comum com você. Ajudaria mais na utilização do comando +unban ID mensagem

**Porque a sua sugestão deve ser adicionada na Loritta?**

Pois é um complemento do comando que já existe e é básico para moderação.

**Considerações Finais**

Acho que agregaria ainda mais se essa função fosse adicionada ao comando principal +unban, assim iria ajudar a pessoa a saber quando for desbanida de tal servidor.

**Comment by MrPowerGamerBR** [comment]
Poderiam usar isso para spammar pessoas na DM com divulgação, por isso essa funcionalidade não existe.
